name: Update Roblox IPs

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Run IP checker
        run: python scripts/check_ips.py
        
      - name: Commit changes
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.com"
          git add data/clean_ips.json hosts
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Roblox IPs [skip ci]"
          git push
